# Generated by Django 4.2.2 on 2023-06-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(default=-2003, max_length=150),
            preserve_default=False,
        ),
    ]
