# Generated by Django 4.2.2 on 2023-07-18 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_version_product_product_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
            preserve_default=False,
        ),
    ]
