# Generated by Django 4.2.2 on 2023-07-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_version_version_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.CharField(max_length=150, verbose_name='Название версии'),
        ),
    ]
