# Generated by Django 4.2.2 on 2023-07-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_version_version_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(verbose_name='Номер версии'),
        ),
    ]
